# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Memo
tagline:             ''
description:         ''
url:                 https://jonghak-lee.github.io
baseurl:             ''
paginate:            1
plugins:             [jekyll-paginate]

# About/contact
author:
  name:              Jonghak Lee
  url:               https://jonghak-lee.github.io
  email:             jonghak.lee@icloud.com

# Custom vars
version:             1.0.0
